version: '3'

tasks:
  setup:
    desc: Setup
    cmds:
      - pnpm install
  start:
    desc: Run development server
    cmds:
      - pnpm run dev
  test:
    desc: Run tests
    cmds:
      - pnpm run test
